name: Build Python App for macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests pyinstaller openpyxl

      - name: Build app with PyInstaller (onedir)
        run: |
          pyinstaller --onedir --hidden-import openpyxl cleaning_script.py

      - name: Remove quarantine attribute
        run: |
          xattr -r -d com.apple.quarantine dist/cleaning_script    

      - name: Zip the dist folder
        run: |
          cd dist
          zip -r cleaning_script-mac.zip cleaning_script

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: dist/cleaning_script-mac.zip
